### ISSUE TITLE
unintelligible voice

### ISSUE THREAD

**Issue by K0EZ** [theeasiestway/android-webrtc-aecm#1]
Hi,

the code is very neat ,thanks for sharing it.
but the sample app, when i turn on AEC, the voice is very unintelligible, i tried to change the delay, aggressive and frequency , the result is the same

**Comment by theeasiestway** [comment]
Hi, the sample app demonstrates that if an echo cancellation is enabled then you won't hear echo of your voice and insofar as in this app only your voice is simultaneously recorded and played back you won't hear anything or you will hear only some fragments of the sound that wasn't processed by AEC. Of cource this app not good enough shows the echo cancellation proccess and idealy this app should transfer the sound between two remote devices. I might do it someday).
