### ISSUE TITLE
version of webRTC this is based on

### ISSUE THREAD

**Issue by zoff99** [theeasiestway/android-webrtc-aecm#2]
can you specify which version of webRTC this is based on? or what commit hash of webRTC?

**Comment by theeasiestway** [comment]
@zoff99 As I said in the readme my repository is based on [this](https://github.com/lhc180/webrtc-based-android-aecm) repository without changing webRTC sources, so according to [this](https://github.com/lhc180/webrtc-based-android-aecm/commit/f0f5fe0d9e0c608c1524c41b6b3753a826b88285) commit the revision of webRTC is **5071**.

**Comment by zoff99** [comment]
@theeasiestway thank you for the information. i hope i can use it in my project.

**Comment by theeasiestway** [comment]
@zoff99 you're welcome if you have any problems then let me know
