### ISSUE TITLE
Clicking the AEC switch simply stops the output sound

### ISSUE THREAD

**Issue by mahaju** [theeasiestway/android-webrtc-aecm#3]
When I press the AECM switch on the user interface it simply stops the output sound
In a normal situation the app sends audio in the microphone o the speaker, but regardless of what I choose in the slider bars, when I turn on the AECM switch, the output just stops

Can you please post a an example of how I can test this program, a sample input to use and what I can expect as the output? I am using this on Samsung Galaxy S7 Android 8.0

**Comment by theeasiestway** [comment]
@mahaju It's a normal behaviour, check my answer [here](https://github.com/theeasiestway/android-webrtc-aecm/issues/1#issuecomment-540305426) where I explain it.

**Comment by mahaju** [comment]
@theeasiestway then how exactly can I see this app's output? Does it send it's output to another device or something? Or record some log file?

**Comment by theeasiestway** [comment]
@mahaju The app actually plays back the sound that was recorded from a device's mic, but insofar as the sound was handled by AECM you either can't hear anything or can hear only some fragments of sound, so the app **doesn't stop** playing the sound after enable AEC. At the moment the app doesn't send the output to another device and doesn't write any log files.
